print ("====BIODATA=====")
print ()
namalengkap = input("Masukan Nama Lengkap Anda : ")
namapanggilan = input("Masukan Nama Panggilan Anda : ")
npm = input("Masukan NPM anda : ")
tempatlahir = input("Tempat Lahir Anda : ")
umur = input("Masukan Umur Anda : ")
telepon= input("Masukkan No.Telepon Anda : ")
alamat= input("Masukan Alamat Anda : ")

print ("=====BIODATA ANDA=====")
print ("Assalamu'alaikum")
print ()
print ("Let me introduce my self. My name is" ,namalengkap, " but you can call me" ,namapanggilan, ". My NPM is" ,npm, ". I was born in" ,tempatlahir, "and i am" ,umur, "years old. I am very glad if you want to invite my house in" ,alamat, ". So, don't forget to call me before with the number" ,telepon, ".")
print ()
print ("Thank you")
